### ISSUE TITLE
raydium

### ISSUE THREAD

**Issue by Haniamin90** [DeFiMasterd/PancakeX-Crosschain-sniping-bot#2]
i dont see raydium in the code, am i missing something ?

**Comment by DeFiMasterd** [comment]
Damn you are right I didn't include that, my bad

**Comment by Haniamin90** [comment]
are you planning to include it or is it available separately ?

**Comment by DeFiMasterd** [comment]
I can do it no problem, can you tell me what exactly you would like the bot to do? Give me a detailed description and I will do it in my free time. Raydium is something I don't have experience with

**Comment by Haniamin90** [comment]
Please DM me on telegram or discord if possible:
xH#9994
https://t.me/Haniamin90
