### ISSUE TITLE
Using another router

### ISSUE THREAD

**Issue by Turgonn** [DeFiMasterd/PancakeX-Crosschain-sniping-bot#4]
Hello,

First of all, thank you for providing that bot opensource for free, I really appreciate that and this is very cool from you.

I want to use another router than Pancakeswap to make a snipe, but when I replace the PCS router adress in the astra.py file with the one I  want to use, I cant make any tx, and they end all reverted. Do you have any idea of what I am doing wrong ?

**Comment by DeFiMasterd** [comment]
Hey, and thanks for such a nice comment. 

Are you replacing the router and factory address for a fork of pancakeswap? If not check the ABI as well
